### ISSUE TITLE
Create 3 gifs to be used in ReadMe.md file

### ISSUE THREAD

**Issue by pavan168** [baby-journey/rn-segmented-progress-bar#14]
1. Single circle
2. Mutiple segments
3. Multiple segments with animation and progress circle

**Comment by Champkinz** [comment]
**Single circle**

![Image](https://user-images.githubusercontent.com/18216773/215086934-c145e17f-e22e-4feb-8c12-c9c8436d15d3.png)

**Comment by Champkinz** [comment]
![Image](https://user-images.githubusercontent.com/18216773/215094792-54f9c2c0-7cca-4d5c-a2f5-bbb5f0e35dec.gif)

**Comment by Champkinz** [comment]
![Image](https://user-images.githubusercontent.com/18216773/215095336-1d3ea2e4-1d8b-4cf3-96b2-5d035061475b.gif)

**Comment by Champkinz** [comment]
![Image](https://user-images.githubusercontent.com/18216773/215096255-849dad74-8f86-476b-9786-39cfc7e09b04.gif)
